site_name: Advanced Journey
repo_url: https://github.com/GabrielBrotas/Advanced-Journey
edit_uri: blob/main/docs/
site_description: My learning related to Architecture
site_author: Gabriel Brotas
remote_branch: gh-deploy

nav:
  - Home: index.md
  - Architecture:
    - "Types of Architecture": Architecture/types-of-architecture.md
    - "Sustainability": Architecture/sustainability.md
    - "Architectural Features": Architecture/architectural-features.md
    - "Design Quality Software": Architecture/design-quality-software.md
  - 'Systems Communication': 
    - SystemsCommunication/index.md
    - REST: SystemsCommunication/REST.md
    - gRPC: SystemsCommunication/gRPC.md
    - GraphQL: SystemsCommunication/GraphQL.md
theme:
  name: mkdocs
  nav_style: dark
  locale: en
