site_name: Advanced Journey
site_url: https://gabrielbrotas.github.io/
repo_url: https://github.com/GabrielBrotas/Advanced-Journey
edit_uri: blob/main/docs/
site_description: My learning related to Architecture
site_author: Gabriel Brotas
remote_branch: gh-deploy
nav:
  - Home: index.md
  - Architecture:
      - "Types of Architecture": Architecture/types-of-architecture.md
      - "Sustainability": Architecture/sustainability.md
      - "Architectural Features": Architecture/architectural-features.md
      - "Design Quality Software": Architecture/design-quality-software.md
  - "Systems Communication":
      - SystemsCommunication/index.md
      - REST: SystemsCommunication/REST.md
      - gRPC: SystemsCommunication/gRPC.md
      - GraphQL: SystemsCommunication/GraphQL.md
  - SOLID:
      - SOLID/index.md
      - "Single Responsibility Principle": SOLID/single-responsability.md
      - "Open-closed Principle": SOLID/open-closed.md
      - "Liskov Substitution Principle": SOLID/liskov-substitution.md
      - "Interface Segregation Principle": SOLID/interface-segregation.md
      - "Dependency Inversion Principle": SOLID/dependency-inversion.md
  - "Domain Driven Design": domain-driven-design.md
  - Microservices: microservices.md
  - Kafka: 
    - Kafka/index.md
    - Topics: Kafka/topics.md
    - 'Producers and Consumers': Kafka/producers-and-consumers.md
    - 'Kafka Connect': Kafka/kafka-connect.md
    - Avro: Kafka/avro.md
theme:
  name: material
  features:
    - tabs
    - content.tabs.link
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    - primary: black
      scheme: purple
      accent: red
        
plugins:
  - search:
      lang: en
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
